### ISSUE TITLE
[Feature]: Publish on Maven Central

### ISSUE THREAD

**Issue by radixdev** [braze-inc/braze-android-sdk#1]
### What problem are you facing?

Please deploy the library on maven central.

### Workarounds

Copied from https://github.com/Appboy/appboy-android-sdk/issues/237

**Comment by radixdev** [comment]
cc @wartingep

Also as an update, moving repositories like this is the first step in our maven central publishing plan.

**Comment by radixdev** [comment]
Hello @wartingep @gabrielittner ,

We're now available on [Maven Central](https://repo.maven.apache.org/maven2/com/braze/) as of version 25.0.0 of the Braze Android SDK. 

Thank you for your patience on this journey,
Braze

**Comment by gabrielittner** [comment]
This is great, thank you
