### ISSUE TITLE
[Bug]: Content Cards impression not logged when setting vertical padding to `Braze.ContentCardsDisplay.Recycler`

### ISSUE THREAD

**Issue by egor-n** [braze-inc/braze-android-sdk#10]
### Braze Android SDK Version

26.1.0; 23.2.1

### Steps To Reproduce

0. Define `Braze.ContentCardsDisplay.Recycler` style with vertical padding:
    ```
    <style name="Braze.ContentCardsDisplay.Recycler">
        <item name="android:paddingTop">4dp</item>
        <item name="android:paddingBottom">4dp</item>
    </style>
    ```
2. Insert `ContentCardsFragment`
3. Send a couple content cards
4. Open the `ContentCardsFragment` screen
5. Close the `ContentCardsFragment` screen

### Expected Behavior

All cards that were on the screen should log impression.

### Actual Incorrect Behavior

None of the cards are logging the impression. When debugging, I saw that `layoutManager.findFirstVisibleItemPosition()` and `layoutManager.findLastVisibleItemPosition()` always return `-1`.

### Verbose Logs

```shell
16:59:29.869  V  The card at position 0 isn't on screen or does not have a valid adapter position. Not logging impression.
16:59:29.872  V  The card at position 1 isn't on screen or does not have a valid adapter position. Not logging impression.
```

**Comment by radixdev** [comment]
Hi @egor-n ,

We can reproduce the issue and will update this thread with a fix. It does appear that the `findFirstVisibleItemPosition()` methods are firing too late/early depending on the padding, like you're seeing.

**Comment by radixdev** [comment]
Hi @egor-n ,

Upon further inspection of the reported issue it doesn't look like we can support adding padding to the RecyclerView in that way. I would suggest some combination of the following (3. specifically):
1. Modifying the `dimens/com_braze_content_cards_divider_height` value 
2. Adding margin/padding to the surrounding container view of the RecyclerView instead of the `RecyclerView` itself.
3. Modifying `ContentCardsDividerItemDecoration`

**Comment by egor-n** [comment]
@radixdev I ended up adding a new `ItemDecoration` like so:

```
class VerticalPaddingDecoration(
    private val paddingPx: Int
) : RecyclerView.ItemDecoration() {
    override fun getItemOffsets(
        outRect: Rect,
        view: View,
        parent: RecyclerView,
        state: RecyclerView.State
    ) {
        val itemPosition = parent.getChildAdapterPosition(view)
        if (itemPosition == RecyclerView.NO_POSITION) {
            return
        }
        if (itemPosition == 0) {
            outRect.top = paddingPx
        }
        val adapter = parent.adapter
        if (adapter != null && itemPosition == adapter.itemCount - 1) {
            outRect.bottom = paddingPx
        }
    }
}

// custom ContentCardsFragment:
class MyContentCardsFragment : ContentCardsFragment() {
    override fun onViewStateRestored(savedInstanceState: Bundle?) {
        super.onViewStateRestored(savedInstanceState)
        contentCardsRecyclerView?.let { recyclerView ->
            recyclerView.addItemDecoration(
                VerticalPaddingDecoration(
                    resources.getDimensionPixelOffset(
                        R.dimen.my_vertical_padding
                    )
                )
            )
        }
    }
}
```
