### ISSUE TITLE
[Bug]: Crash in HTML IAM when calling `window.open`

### ISSUE THREAD

**Issue by Minishlink** [braze-inc/braze-android-sdk#11]
### Braze Android SDK Version

26.3.2

### Steps To Reproduce

Hello, after an upgrade from 25 to 26.3.2 (React Native module 5 => 6), we noticed that the app crashes when a user clicks on the following "Close" link. It seems related to `window.open`.

```html
<html>
<meta charset="utf-8">
<meta name="viewport" content="viewport-fit=cover, initial-scale=1, maximum-scale=1">
<body style="padding: 50px;">
<a href="#" onclick="window.open('myScheme://myPath')">Close</a>
</body>
</html>
```

Note that a `button` will do nothing but won't crash.

Stacktrace below :

```
System.err  W  android.os.FileUriExposedException: file://null/# exposed beyond app through Intent.getData()
                         W      at android.os.StrictMode.onFileUriExposed(StrictMode.java:2208)
                         W      at android.net.Uri.checkFileUriExposed(Uri.java:2407)
                         W      at android.content.Intent.prepareToLeaveProcess(Intent.java:11914)
                         W      at android.content.Intent.prepareToLeaveProcess(Intent.java:11863)
                         W      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1833)
                         W      at android.app.Activity.startActivityForResult(Activity.java:5507)
                         W      at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
                         W      at android.app.Activity.startActivityForResult(Activity.java:5465)
                         W      at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
                         W      at android.app.Activity.startActivity(Activity.java:5963)
                         W      at android.app.Activity.startActivity(Activity.java:5930)
                         W      at com.braze.ui.inappmessage.views.InAppMessageHtmlBaseView$messageWebView$7.onCreateWindow(InAppMessageHtmlBaseView.kt:147)
```

### Expected Behavior

No crash

### Actual Incorrect Behavior

Crashes

### Additional Information

This works great on iOS and on the Android SDK 25.

Note that replacing the redirection with `window.location.href = ` somehow works.

```html
<a href="#" onclick="window.location.href = 'myScheme://myPath'">Close</a>
```

**Comment by radixdev** [comment]
Hi @Minishlink ,

We're investigating this and will get back to you shortly.

**Comment by radixdev** [comment]
In the meantime, can you provide [verbose logs](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/) from your app starting a bit before and a bit after you click that button in the HTML in app message?

**Comment by radixdev** [comment]
Hi @Minishlink ,

Please see the [26.0.0 changelog](https://github.com/braze-inc/braze-android-sdk/blob/f7180f279912252e90c05f7b2cea823141944416/CHANGELOG.md#breaking-1) about how to disable this functionality. We introduced a feature that allows for link targets to be handled differently in that version and as a result, `window.open` broke in the process. 

If disabling that feature does not work for you, I would separately recommend `window.location.href` as you pointed out earlier.

**Comment by Minishlink** [comment]
Uh, is it that hard to acknowledge there is a bug?
What if you want to keep that feature and still use `window.open`?
Our marketing teams would have to go over each HTML IAM and replace manually `window.open` by `window.location.href`
I mean, you can't expect all your users to know that `window.open` is buggy and go for `window.location.href`...
