### ISSUE TITLE
[Bug]: Braze Accent Color 

### ISSUE THREAD

**Issue by BrazeCJ** [braze-inc/braze-android-sdk#15]
### Braze Android SDK Version

25.0.0

### Steps To Reproduce

I tried to use the accent icon color function in the Braze function, but the colors don't seem to be compatible.
(https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/#step-3-configure-notification-icons)

### Expected Behavior

To confirm proper color application, we only carried out a basic push-linked campaign.

### Actual Incorrect Behavior

We know that starting from Android specifiy version and higher, the icon color changes differently depending on the user-defined theme, but the braze icon accent color is not applied properly even when the theme is not applied.

### Verbose Logs

```shell
There is no separate verbose log, and we share the braze xml file applied by the customer.

[braze.xml]

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="com_braze_custom_endpoint" translatable="false">sdk.iad-05.braze.com</string>

    <bool name="com_braze_firebase_cloud_messaging_registration_enabled" translatable="false">true</bool>

    <bool name="com_braze_handle_push_deep_links_automatically">true</bool>
    <bool name="com_braze_push_deep_link_back_stack_activity_enabled">true</bool>
    <string name="com_braze_push_deep_link_back_stack_activity_class_name">com.app.celebshop.main.MainActivity</string>

    <drawable name="com_braze_push_small_notification_icon">@drawable/ic_small_launcher</drawable>
    <drawable name="com_braze_push_large_notification_icon">@mipmap/ic_launcher</drawable>
    <color name="com_braze_default_notification_accent_color">@color/sys_background_coral</color>
    <bool name="com_braze_push_notification_html_rendering_enabled" translatable="false">true</bool>
</resources>
```

### Additional Information

<img width="322" alt="스크린샷 2023-10-10 오전 9 53 13" src="https://github.com/braze-inc/braze-android-sdk/assets/142372954/7a8f904a-776f-48b3-967c-5ee844ecc097">
[Braze_icon_image.zip](https://github.com/braze-inc/braze-android-sdk/files/12851600/Braze_icon_image.zip)

**Comment by radixdev** [comment]
1. In line with https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/#step-2-conform-small-icons-to-design-guidelines, can you share the small icon drawable file (the `@drawable/ic_small_launcher` png) here?
2. Can you also share the color argb of `@color/sys_background_coral` here as well?
3. What device and API version was this tested on?

**Comment by BrazeCJ** [comment]
1. In line with https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/#step-2-conform-small-icons-to-design-guidelines, can you share the small icon drawable file (the @drawable/ic_small_launcher png) here?

=> It is included in the attached file provided in the previous answer and I will forward it to you again.
![ic_small_launcher](https://github.com/braze-inc/braze-android-sdk/assets/142372954/c64c91bf-8202-4307-8598-8f5f9125d09c)

2. Can you also share the color argb of @color/sys_background_coral here as well?
=>I share the color argb  #FF7873

3. What device and API version was this tested on?
=>The SDK version applied to the client is 25.0.0, and the test device model is "SM-S911N(Android 13)".
=> What does the API version you requested to mean?

Please above the check.

Thanks,
BrazeCJ

**Comment by BrazeCJ** [comment]
Are there any updates regarding the above?
