### ISSUE TITLE
[Bug]: Black screen visible on Notification click with Android 14

### ISSUE THREAD

**Issue by csidhiwala** [braze-inc/braze-android-sdk#17]
### Braze Android SDK Version

com.appboy:android-sdk-ui:24.2.+

### Steps To Reproduce

Steps to reproduce : 

1. Integrate appboy/braze sdk-ui with application
2. Launch application
3. Send push notification to application when it's in foreground / background [Don't kill application]
4. Click on notification present in notification bar
5. Application behaves as expected but it will leave one black screen in background as another instance of application.

Check attached video

### Expected Behavior

When application in foreground or background and user clicks on notification to redirect on expected screen, it should not leave black window as another app instance in background.

### Actual Incorrect Behavior

When application is in foreground / background and user clicks on notification present in notification bar to redirect on specific page, it's triggering another instance of application with blank/black screen in background as shown in attached video

### Additional Information

[Multiple_Instance issue Android 14.webm](https://github.com/braze-inc/braze-android-sdk/assets/111134824/67de208a-235e-41e1-9ee0-6a90147b7ad5)

**Comment by radixdev** [comment]
Please update to SDK version 29.0.1, which contains a fix for this issue.
