### ISSUE TITLE
[Bug]: requestContentCardsRefresh() not refreshing the content cards

### ISSUE THREAD

**Issue by Jafar-Al-Rashid** [braze-inc/braze-android-sdk#18]
### Braze Android SDK Version

29.0.1

### Steps To Reproduce

         braze.requestContentCardsRefresh()

### Expected Behavior

Local content cards list should get updated, remove dismissed cards or add new ones

### Actual Incorrect Behavior

The content cards list is not changed

The refresh works as expected when using the deprecated method instead

        braze.requestContentCardsRefresh(
            fromCache = false
        )

**Comment by radixdev** [comment]
Please provide [verbose logs](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/#android-verbose-logging) of that method being called.
