### ISSUE TITLE
[Feature]: Jetpack Compose Support

### ISSUE THREAD

**Issue by radixdev** [braze-inc/braze-android-sdk#2]
### What problem are you facing?

I would like to know if there are any plans for Jetpack Compose support in near future?

In our new App that is completely build of Jetpack Compose components (UI, Navigation, etc) we still need to use XML layouts for our customized views like In-App-Modal and implement a custom Braze Navigator to work with the new compose navigation.

Technically it is working, but preference would be to have support for it to avoid workarounds.

Thank you!

### Workarounds

Cloned from https://github.com/Appboy/appboy-android-sdk/issues/208

**Comment by radixdev** [comment]
cc @fintasys

**Comment by radixdev** [comment]
Copied from original:

Oh sorry for the late reply!

Ah I see, too bad. Thank you for the information!

About the workaround, we haven't found a way to directly access compose navigation with `AppboyNavigator`. So we made a custom Implementation of it and just creating and starting normal intents inside `gotoUri`. Compose Navigation then will handle the intent and open the associated screen. The disadvantage of this method is that the transition isn't as smooth as if we use compose navigation directly - all compose components need to be recreated with this method.

Here is a code snipped to make it more clear:
Screen-Navigation
```
fun NavGraphBuilder.screenNavigation(
    navController: NavController,
) {
    composable(
        route = "....",
        arguments = listOf(
            ...
        ),
        deepLinks = listOf(
            navDeepLink {
                uriPattern = DEEPLINK_PATTERN
            },
        )
    )
```
Custom BrazeNavigator
```
    override fun gotoUri(context: Context, uriAction: UriAction) {
        Timber.d("Executing Uri action from Channel ${uriAction.channel}: Extras: ${uriAction.extras}")

        // Let Braze handle open website requests (non-AppLink)
        if (uriAction.useWebView) {
            return super.gotoUri(context, uriAction)
        }

        deepLinkIntent?.action = Intent.ACTION_VIEW
        deepLinkIntent?.data = uriAction.uri

        taskStackBuilder
            .addNextIntentWithParentStack(deepLinkIntent)
            .getPendingIntent(0, PendingIntent.FLAG_UPDATE_CURRENT)
            ?.send() ?: throw IllegalStateException("Failed to send deep link pending intent is null")
    }
```

**Comment by bryanlogan** [comment]
@Fintasys We did release Jetpack Compose for Content Cards in our latest release. Let us know if you have any feedback.

**Comment by Fintasys** [comment]
@bryanlogan Sorry for late reply. Great to see progress on the Jetpack Compose front. Unfortunately we always used custom UI for Content Cards, so we have our own Jetpack Compose implementation since the beginning. 
Any timeline for Jetpack Compose based In-App-Message?

**Comment by bryanlogan** [comment]
Take a look at our Content Card  implementation. We have some really nice ways to easily implement your own UI with it.

Are there any certain issues you're hitting with InApp Messages right now?  We just want to know what use cases to look out for.

Thanks.
