### ISSUE TITLE
[Bug]: Android resource linking failed

### ISSUE THREAD

**Issue by vinaykumar2197** [braze-inc/braze-android-sdk#23]
### Braze Android SDK Version

29.0.1

### Steps To Reproduce

  > Android resource linking failed
     /root/.gradle/caches/transforms-3/c65ea9d3bc20d0320da8dfecbb75b1d3/transformed/commons-0.8.5.5/res/layout/md_preference_custom.xml:21: warn: generated id 'android:id/icon' for external package 'android'.
     error: resource style/Braze.ContentCards.BannerImage (aka com.*.mobile.debug:style/Braze.ContentCards.BannerImage) not found.
     error: failed linking references.

### Expected Behavior

I am not able to sync the project because of this issue while trying to upgarde the braze sdk this issue starts coming from version 29 

### Actual Incorrect Behavior

NA

### Verbose Logs

```shell
NA
```

### Additional Information

NA

**Comment by radixdev** [comment]
Hi @vinaykumar2197 ,

Can you provide a sample application that reproduces the issue and concrete steps on how to reproduce?

**Comment by radixdev** [comment]
Hey @vinaykumar2197 ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
