### ISSUE TITLE
[Bug]: getInstance(Context) method may unexpectedly provide different Braze instances

### ISSUE THREAD

**Issue by amatsehor-atd** [braze-inc/braze-android-sdk#26]
### Braze Android SDK Version

30.0.0

### Steps To Reproduce

Create two singleton entities with a Braze instance field (created with the same Context instance)

`class BrazeContentCardsHandler(private val braze: IBraze)`
`class BrazeAnalyticsHandler(private val braze: IBraze)`

### Expected Behavior

As specified in a [KDoc](https://braze-inc.github.io/braze-android-sdk/kdoc/braze-android-sdk/com.braze/-braze/-companion/get-instance.html?query=fun%20getInstance(context:%20Context):%20Braze), the same `Braze` instance (singleton) should be provided

### Actual Incorrect Behavior

Sometimes two different instances are created with the first being `isInstanceStopped == true`

<img width="400" alt="Screenshot 2024-03-05 at 14 03 41" src="https://github.com/braze-inc/braze-android-sdk/assets/127213840/1dd73f65-3054-4640-ad8f-7355d1870a95">

**Comment by bryanlogan** [comment]
Are you calling these in the Application::onCreate()?  Also, is your API key in an XML file or dynamic configuration?

The object is initialized when `getInstance(Context)` is called, and there are a few scenarios where you could get a second instance created, and that's fine. Overall, you should always be using `Braze.getInstance(Context)` and not caching that value.

Is there some larger problem you're investigating?

**Comment by amatsehor-atd** [comment]
I've been investigating why sometimes I'm not getting incoming Content Cards with messages like "this content cards is for user #1234567, current user: (blank)"

I feel it's a little counter-intuitive that the method:
1. Specifically documented as "that returns the Braze **_singleton_**" (a pattern that by [definition](https://refactoring.guru/design-patterns/singleton) is developed to ensure that you'll always get the single instance of a class)
2. Also documented with "All requests to Braze are made through **_this instance_**"

may, in some cases, return different instances.

In case it is some sort of expected/normal behavior, I'd kindly ask you to document this behavior a bit clearer, so we wouldn't rely on `getInstance(Context)` being an actual singleton method.

**Comment by bryanlogan** [comment]
Are you using `wipeData()` or `disableSdk()` or have a misconfigured API key?  Those are issues where you could have new instances.

I'll update the KDOC since "singleton" doesn't apply when you're in these situations.

For the Content Card issues, feel free to reach out to support so we can help you resolve those.

**Comment by amatsehor-atd** [comment]
Yes, we use `disableSdk()` in certain situations

Thank you for your assistance

**Comment by radixdev** [comment]
We have updated our documentation as per our conversation above.
