### ISSUE TITLE
[Bug]: IAM not dismissed if as action a new activity is started

### ISSUE THREAD

**Issue by danielardelean** [braze-inc/braze-android-sdk#35]
### Braze Android SDK Version

31.1.0

### Steps To Reproduce

**Prerequisites:**
-	Configure an in-app messaging campaign that has a button with `Deeplink into app`/`Open web URL` on-click behavior and set a URL for it.
-	In the app, set a `CustomHtmlInAppMessageActionListener` with the `onOtherUrlAction` function overridden. When `onOtherUrlAction` is triggered, start Activity B and return true
-	The in-app message is displayed on Activity A

**Steps:**

1.	Tap on the in-app message button
2.	From Activity B, (press back to) return to Activity A

### Expected Behavior

No in-app message is displayed on Activity A

### Actual Incorrect Behavior

The in-app message is still displayed on Activity A

### Additional Information

Notes: 

- The expected behavior is obtained if a post delay of about 300 ms is added to the start of Activity B.
- I get the same behavior if I set a `CustomInAppMessageManagerListener` with the `onInAppMessageButtonClicked` function overridden.

**Comment by bryanlogan** [comment]
How close is your custom listener to https://github.com/braze-inc/braze-android-sdk/blob/master/android-sdk-ui/src/main/java/com/braze/ui/inappmessage/listeners/DefaultInAppMessageWebViewClientListener.kt ?

I would be good to get logs from when this occurs. If you don't want to post those here, you can always reach out to Braze support.

**Comment by danielardelean** [comment]
Not much. My custom listener overrides only the `onOtherUrlAction` fun and is something like this:

```
class CustomHtmlInAppMessageActionListener : IHtmlInAppMessageActionListener {
        override fun onOtherUrlAction(
            inAppMessage: IInAppMessage,
            url: String, queryBundle: Bundle
        ): Boolean {
            if (isValidUrl(url)) {
                startActivity(ActivityB)

                BrazeInAppMessageManager.getInstance().hideCurrentlyDisplayingInAppMessage(false)
                return true
            }

            return super.onOtherUrlAction(inAppMessage, url, queryBundle)
        }
    }
```

The only similarity is `hideCurrentlyDisplayingInAppMessage(false)` call.

**Comment by bryanlogan** [comment]
What happens if you call hideCurrentlyDisplayingInAppMessage before the startActivity?

**Comment by danielardelean** [comment]
I get the same behavior

**Comment by bryanlogan** [comment]
OK, it looks like there's an issue with the animating out and the Activity becoming backgrounded. Try this:

```
inAppMessage.animateOut = false
BrazeInAppMessageManager.getInstance().hideCurrentlyDisplayingInAppMessage(false)
startActivity(...)
```

I'll get a ticket written for the trying to fix this use case, but this should help in the meantime.

**Comment by bryanlogan** [comment]
Release 32.0.0 has this fix. Closing this issue now.
