### ISSUE TITLE
[Bug]: The workspace key is incorrectly set.

### ISSUE THREAD

**Issue by woosang-nolbal** [braze-inc/braze-android-sdk#37]
### Braze Android SDK Version

31.1.0

### Steps To Reproduce

Development workspace key A and
When the production workspace key B exists,

brazeAnalyticsUtils.Development workspace key A and
When the production workspace key B exists,

brazeAnalyticsUtils.setConfig(apiKey = A)
Like this, it is set with the development workspace A key, but the header of the Braze API looks at the key of B.

### Expected Behavior

When braze AnalyticsUtils.setConfig(apiKey = A) does this, APIKey must be set. (A)

When braze AnalyticsUtils.setConfig(apiKey = B) does this, APIKey must be set. (B)

### Actual Incorrect Behavior

When braze AnalyticsUtils.setConfig(apiKey = A) does this, APIKey must be set. (B)

When braze AnalyticsUtils.setConfig(apiKey = B) does this, APIKey must be set. (B)

**Comment by woosang-nolbal** [comment]
Please solve the issue

**Comment by bryanlogan** [comment]
Are you sure the Braze instance isn't running when you're trying to set the config?  You can call `Braze.disableSdk(context)`, and then set the config, and then enable the SDK.

AnalyticsUtils isn't our code, so we can't tell what's going on in that code.

Verbose logs would be very helpful in this case.

**Comment by woosang-nolbal** [comment]
I'm sorry.
Braze AnalyticsUtils.setConfig is the code I created.
Logic calls BrazeConfig.Builder().setApiKey(A) like this.
When you call BrazeConfig.Builder().setApiKey(A), the result is set to the key in B.

**Comment by bryanlogan** [comment]
That only sets the API key in the BrazeConfig object. Can you try:

```
val brazeConfig = BrazeConfig.Builder()
        .setApiKey("api-key-here")
        .build()
Braze.configure(this, brazeConfig)
```

Again, the SDK should not be in use, so either right at startup or call `Braze.disableSdk()`

**Comment by woosang-nolbal** [comment]
Thank you. I'll give it a try

**Comment by woosang-nolbal** [comment]
```
        Braze.disableSdk(context)
        BrazeConfig.Builder().apply {
            setApiKey(apiKey)
            setCustomEndpoint(endPointKey)
            setFirebaseCloudMessagingSenderIdKey(sendId)
            setIsFirebaseCloudMessagingRegistrationEnabled(isFirebaseCloudMessageEnabled)
            setHandlePushDeepLinksAutomatically(isDeepLinkAutomatically)
            setSmallNotificationIcon(notificationIcon)
            setIsPushWakeScreenForNotificationEnabled(false)
        }.let {
            Braze.enableSdk(context)
            Braze.configure(context, it.build())
            braze = Braze.getInstance(context)
        }
```
I solved it with the code below
Thank you. :)

**Comment by bryanlogan** [comment]
Great. Also, don't keep around the copy of `Braze.getInstance()`, just get the instance every time.
