### ISSUE TITLE
[Feature]: Setup braze api_key by Kotlin

### ISSUE THREAD

**Issue by PhanVanLinh** [braze-inc/braze-android-sdk#38]
### What problem are you facing?

From this document
https://www.braze.com/docs/developer_guide/platform_integration_guides/flutter/flutter_sdk_integration/#step-1-integrate-the-braze-library, we can set the `com_braze_api_key` from xml file in Android while iOS is using swift to setup api key. 

Is there any security issue if we define the api key within xml? If yes, can we have a way to set the API key by Kotlin, similar to what iOS does, then we might store the api key in keystore or applying some obfuscation/ encrypt to protect it. 

### Workarounds

NA

**Comment by bryanlogan** [comment]
This document should help.

https://www.braze.com/docs/developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration
