### ISSUE TITLE
[Bug]: In-App Message Body Alignment Issue: Always Aligned to View Start

### ISSUE THREAD

**Issue by Jaypatelbond** [braze-inc/braze-android-sdk#43]
### Braze Android SDK Version

32.1.0

### Steps To Reproduce

In the latest update of the Braze SDK for Android, the in-app message body alignment is not behaving as expected. Despite setting the alignment through the Braze dashboard, the message body is consistently aligned to the view's start. This issue persists across multiple message types, and the alignment settings configured in the dashboard do not take effect in the app.

### Expected Behavior

The message body should align based on the settings specified in the Braze dashboard. Like Start, End or Center

### Actual Incorrect Behavior

The message body is always aligned to the start of the view, ignoring the configured alignment setting.

### Additional Information

- **Braze SDK version:** 32.1.0 and 32.0.0
- **Android OS version:** Tested in Android 11 to 15
- **Device:** Pixel 6A API 30 to 35

**Comment by bryanlogan** [comment]
We found this already and it'll be out in the next fix.  If you don't want to wait for the next release, you can modify the com_braze_inappmessage_*.xml files to remove the `android:textAlignment="viewStart"` line.

**Comment by bryanlogan** [comment]
This is fixed in the 33.0.0 release.
