### ISSUE TITLE
[Bug]: HTML In-App message not dismissed after calling brazeBridge.closeMessage() with deeplink href.

### ISSUE THREAD

**Issue by SteveJ-TRR** [braze-inc/braze-android-sdk#44]
### Braze Android SDK Version

32.1.0

### Steps To Reproduce

```
<td style="padding:0 0 0 0" align="center">
<a href="deeplink://products?id={{item.item_id}}" onclick="brazeBridge.logClick('1');brazeBridge.closeMessage()">
<img src="https://braze-images.com/appboy/communication/assets/image_assets/images/6306adceeb5b1b1b836c8e75/original.png?1661382094" style="display: block; padding: 0;" width="100%" border="0" alt="SHOP NOW"></a>
</td>
```
1) Create in-app message with deeplink and closeMessage onClick
2) Click deeplink. User navigates to correct screen
3) User navigates back.
4) In-App message remains, but is not interactable. User is able to interact with underlying screen, but in-app message remains visible.

### Expected Behavior

In-App message should be dismissed after clicking the deeplink with the closeMessage onClick.

### Actual Incorrect Behavior

In-App Message is not dismissed after clicking the deeplink with the closeMessage onClick and user is able to interact with underlying screen.

Before clicking in-app message is blocking underlying screen. As seen here with layout bounds visible.
![Screenshot_20241010-085833](https://github.com/user-attachments/assets/57156db2-63c1-491a-90e5-f2e32035e15f)

After the user navigates back the in-app message no longer has focus and use is able to interact with the underlying screen.
![Screenshot_20241010-085903](https://github.com/user-attachments/assets/0204cc5f-ad09-4d97-b5d7-a50826450a7a)

**Comment by radixdev** [comment]
Hi @SteveJ-TRR ,

The SDK will automatically handle closing the IAM after the deeplink click. Can you try removing the call to `brazeBridge.closeMessage()`?
