### ISSUE TITLE
[Bug]: Braze SDK is not correctly integrated into your project.

### ISSUE THREAD

**Issue by F1-github** [braze-inc/braze-android-sdk#47]
### Braze Android SDK Version

33.1.0

### Steps To Reproduce

<img width="918" alt="스크린샷 2024-11-19 오후 3 03 41" src="https://github.com/user-attachments/assets/70162a67-41a5-4953-b871-02b57d1de6df">

### Expected Behavior

The specific utility class (BrazeFileUtils) is not accessible or properly imported.

Add Braze JavaScript interface functionality.

### Actual Incorrect Behavior

I am trying to add the Braze JavaScript interface in Kotlin.

I am following the Braze Android guide here:
[Adding Braze JavaScript Interface](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/advanced_use_cases/adding_braze_js_interface#braze-javascript-interface)

However, BrazeFileUtils and inAppMessage are unresolved references. The guide doesn't mention any specific imports to add. Are there any imports or additional setup required that I might be missing?

**Comment by bryanlogan** [comment]
In the CHANGELOG, we updated it in 33.1.0 to handle both Banners and In-App Messages.

`val javascript = context.assets.getAssetFileStringContents("braze-html-bridge.js")`

I'll get the documentation updated.

**Comment by F1-github** [comment]
If I modify it according to the method you provided, should the inAppMessage object in

```
val javascriptInterface = InAppMessageJavascriptInterface(context, inAppMessage)
```
also be retrieved?

I have declared

```
val javascript = context.assets.getAssetFileStringContents("braze-html-bridge.js")
```

but the inAppMessage is not being invoked.

**Comment by bryanlogan** [comment]
Are you still calling `webview.loadUrl()` and the other lines as well?  The documentation should be correct for those other lines.

You can use [this](https://github.com/braze-inc/braze-android-sdk/blob/13e5a748d7c7156a4c6ae356768b857df3fe6a87/android-sdk-ui/src/main/java/com/braze/ui/BrazeWebViewClient.kt#L111) as a guide on what it should look like.

What are you trying to do with the custom WebView? I'm wondering if it's needed in your situation.

**Comment by F1-github** [comment]
I want to add a Braze JavaScript interface to enable data exchange between native and WebView and handle in-app message events.

Recently, when clicking on a Braze in-app message, a new session is being initiated similar to a push notification, causing the app to open in the web view. This has resulted in some sessions where the distinction between the app and web is not properly maintained. We have concluded that some modifications are needed in the SDK to address this issue.

**Comment by bryanlogan** [comment]
OK, you should reach out to Braze Support because it seems like your use case is a little complex. I'm going to close this issue because we have the documentation update fixed and it should be released soon.
