### ISSUE TITLE
[Bug]: Register activity lifecycle callbacks

### ISSUE THREAD

**Issue by zhangwenxiang26** [braze-inc/braze-android-sdk#5]
### Braze Android SDK Version

com.braze:android-sdk-ui:24.3.0

### Steps To Reproduce

Register activity lifecycle callbacks  Android Studio prompts:

![register_callbacks](https://github.com/braze-inc/braze-android-sdk/assets/19923561/30527350-f7c6-4ba3-bf90-2779147bd70f)

However, Android Studio can compile normally.

### Expected Behavior

Android Studio does not have a red line prompt.

### Actual Incorrect Behavior

Perhaps this is a problem caused by Android Studio.

**Comment by radixdev** [comment]
1. Does this issue persist with a command line `./gradlew build`?
2. According to our kdoc https://braze-inc.github.io/braze-android-sdk/kdoc/braze-android-sdk/com.braze/-braze-activity-lifecycle-callback-listener/index.html we are still extending from the proper class.
3. Can you click into the source of our listener there and see what it extends? (and screenshot it here)

I would agree in thinking that this is purely an Android Studio issue.

**Comment by zhangwenxiang26** [comment]
Java

![image](https://github.com/braze-inc/braze-android-sdk/assets/19923561/27216039-b51a-47d5-bc14-48c90bbf879e)


![image](https://github.com/braze-inc/braze-android-sdk/assets/19923561/ca5eb747-49f4-4e05-87c4-613632e747e4)

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Kotlin
![image](https://github.com/braze-inc/braze-android-sdk/assets/19923561/f8624f58-bcaa-48e9-929f-73a239ccfd6e)

![image](https://github.com/braze-inc/braze-android-sdk/assets/19923561/53fe4ee2-7502-4382-9e70-f65a7984d515)


There is no red line prompt when using kotlin.
