### ISSUE TITLE
the return value of remoteMessage.getNotification() is null.

### ISSUE THREAD

**Issue by zhangwenxiang26** [braze-inc/braze-android-sdk#6]
### Braze Android SDK Version

com.braze:android-sdk-ui:24.3.0

### Steps To Reproduce

Test Braze push notification.

by Braze dashboard creat campaign and send push notification.

![image](https://github.com/braze-inc/braze-android-sdk/assets/19923561/eb9bc302-59d7-4cae-817a-4fa78759ec3b)

I already have a Firebase Messaging Service registered ------> MySelfFCMService 

public class MySelfFCMService extends FirebaseMessagingService {
    @Override
    public void onNewToken(@NonNull String token) {
        super.onNewToken(token);
    }
    @Override
    public void onMessageReceived(@NonNull RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);
//        if (BrazeFirebaseMessagingService.handleBrazeRemoteMessage(this, remoteMessage)) {
//            // This Remote Message originated from Braze and a push notification was displayed.
//            // No further action is needed.
//            return;
//        }
        RemoteMessage.Notification notification = remoteMessage.getNotification();
        if (notification != null) {
            String title = notification.getTitle();
            String body = notification.getBody();
        }
    }
    @Override
    public void onDeletedMessages() {
        super.onDeletedMessages();
    }
}

When I clicked the Send Test button, 

![unnamed](https://github.com/braze-inc/braze-android-sdk/assets/19923561/5e224c1d-de31-419b-8632-4091166feb14)

the method onMessageReceived(@NonNull RemoteMessage remoteMessage) of the MySelfFCMService class was called. 

However, I am unable to obtain the title and body of this notification through the class RemoteMessage.Notification.

        RemoteMessage.Notification notification = remoteMessage.getNotification();
        if (notification != null) {
            String title = notification.getTitle();
            String body = notification.getBody();
        }

Because the return value of remoteMessage.getNotification() is null. notification == null ,I cannot execute the following code:

            String title = notification.getTitle();
            String body = notification.getBody();

But, by firebase dashboard send push notification , 
I can obtain the title and body through notification, 

        if (notification != null) {
            String title = notification.getTitle();
            String body = notification.getBody();
        }

### Expected Behavior

  

if (notification != null) {
            String title = notification.getTitle();
            String body = notification.getBody();
  }

### Actual Incorrect Behavior

 the return value of remoteMessage.getNotification() is null. notification == null ,I cannot execute the following code:

            String title = notification.getTitle();
            String body = notification.getBody();

### Additional Information

I want to know if this situation is normal?

Is this result caused by an issue with my operating steps on the Braze dashboard?

Is that the design of Braze Sdk?

**Comment by bryanlogan** [comment]
The SDK is working as designed.  The push is a data push that gets converted by the Braze SDK.  The code you have commented out is correct.  If the push is for Braze, let the Braze SDK handle it.

What are you attempting to do?  I'm wondering if the push notification callback event could be helpful in your situation. Please let us know your use case.

https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/customization/custom_event_callback

**Comment by zhangwenxiang26** [comment]
Okay, I understand. Thank you very much.

**Comment by frsisalima** [comment]
Hi @bryanlogan, the problem here is that if the notification is not sent with a presentation (only with "data"), the Android system delegates it to the app to handle. The issue we have detected is that when the app is closed and a notification arrives, it causes the app to restart in the background, resulting in an overload of requests to our backend due to the thousands of installations we have.

The desired behavior is that if the app is completely closed, the notification should only be shown in the system's notification bar (for this, the "notification" field of the push message must not be null).

**Comment by radixdev** [comment]
Hi @frsisalima ,

I would recommend contacting support@braze.com and filing a product request for FCM notification messages. We currently do not support notification messages since we would lose analytics capabilities for push.
