### ISSUE TITLE
[Feature]: IsAnonymous getter for BrazeUser

### ISSUE THREAD

**Issue by Fintasys** [braze-inc/braze-android-sdk#7]
### What problem are you facing?

Since Braze doesn't support any logout method, we would like to identify if the current user is from fresh installation (anonymous state) or after user has logged out in order to deal with Braze events differently (log directly or queue upon next login) 

### Workarounds

Probably we can introduce a shared preference to indicate if the user has logged in before or not.

### Ideal Solution

Ideally it would be nice if we could access the state directly from the Braze User.

### Other Information

Alternatively I would like to confirm what is the specifications for `BrazeUser.userId` when the user is anonymous - will it return a UUID or an empty string? Tests so far (SDK 25.0.0) seems it is empty string.

**Comment by bryanlogan** [comment]
Yes, when the userId is an empty string, the user is anonymous. 

Here's some additional information: https://www.braze.com/docs/user_guide/data_and_analytics/user_data_collection/user_profile_lifecycle/

Note this section:

> 2) An anonymous user is identified as an already existing user: If the external_id already exists in Braze’s platform, then this user was previously identified as a user in the system in some other way, e.g., via another device (such as on tablet) or through imported user data. As such, you already have a user profile for this user. In this instance, Braze orphans the anonymous user, removing it from your user base so we don’t incorrectly inflate user counts. Campaign/Canvas analytics and device information is merged from the anonymous profile, however attributes and events will not be merged and need to be handled manually.

**Comment by Fintasys** [comment]
> Yes, when the userId is an empty string, the user is anonymous.
I can't find this information anywhere documented 🤔 would it makes sense to document it or add a getter like I proposed?

**Comment by bryanlogan** [comment]
It's from that same page. It's might be a little confusing because it's talking about `external_id`, but when it's from the SDK, that `external_id` is called `userId`

> Any user without a designated external_id is called an anonymous user.
