### ISSUE TITLE
[Bug]: Notification runtime permission, POST_NOTIFICATIONS

### ISSUE THREAD

**Issue by MrJero** [braze-inc/braze-android-sdk#9]
### Braze Android SDK Version

26.0.0

### Steps To Reproduce

targetSdkVersion: 33
implementation "com.braze:android-sdk-ui:26.0.0"

### Expected Behavior

We should show the notification permission flow.

### Actual Incorrect Behavior

The notification permission flow is not working on Android 13.

### Additional Information

Hi there,

Updating the targetSdkVersion to 33 we’re experimenting with some issues with the Notification Permission.

In our project we're using:

targetSdkVersion: 33
implementation "com.braze:android-sdk-ui:26.0.0"

We realized in devices with Android 13 the Push notification permission is not shown.
So, since from API 33 and above in Android we need to ask for that permission in a different way, it's called POST_NOTIFICATIONS.
https://developer.android.com/develop/ui/views/notifications/notification-permission

just wondering if this is something that you will address and give us support for that, or is something that we should handle on our side?

Thanks in advance
Jero

**Comment by radixdev** [comment]
Hi @MrJero ,

We would need a few things to proceed with an investigation here:

1. Detailed reproduction steps.
2. Verbose logs of the issue occurring.
3. The device model and API version of the device used for the test.

Additionally, our SDK already asks for that permission in https://github.com/braze-inc/braze-android-sdk/blob/4b7004ea60822fa4ff058a503969078923c70c19/android-sdk-ui/src/main/AndroidManifest.xml#L4.

**Comment by MrJero** [comment]
more information:
- https://kubiakdev.medium.com/notification-permission-request-on-android-13-part-1-the-flow-318c046cf2ff
- https://proandroiddev.com/notification-runtime-permission-android13-190c796254d5

**Comment by MrJero** [comment]
I solved it on our side, thanks!
